apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:xlr:redis"]'
  labels:
    cattle.io/creator: norman
  name: redis
  namespace: xlr
  selfLink: /api/v1/namespaces/xlr/services/redis
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workloadID_redis: "true"
  sessionAffinity: None
  type: ClusterIP

