---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: audit_and_reporting
  children:
  - name: Ecommerce
    type: artifactory.Server
    url: http://artifactory:8081/artifactory
    username: admin
    password: !value "artifactory_Server_Ecommerce_password"
  - name: Ecommerce
    type: blackduck.Server
    url: https://blackduck.xebialabs.com
    username: xebialabs
    password: !value "blackduck_Server_Ecommerce_password"
  - name: Ecommerce
    type: fortify.Server
    url: http://xl-chkmarx-poc.xebialabs.com:9000/ssc/
    username: admin
    password: !value "fortify_Server_Ecommerce_password"
  - name: Ecommerce
    type: git.Repository
    url: http://gogs:3000/xebialabs/petclinic-artifactory.git
    username: xebialabs
    password: !value "git_Repository_Ecommerce_password"
  - name: Ecommerce
    type: jenkins.Server
    url: http://jenkins:8080
    username: admin
    password: xebialabs
  - name: Ecommerce
    type: jira.Server
    url: https://xebialabs.atlassian.net
    username: !value "jira_user"
    password: !value "jira_password"
  - name: Ecommerce
    type: servicenow.Server
    url: !value "snow_url"
    username: !value "snow_username"
    password: !value "snow_password"
  - name: Ecommerce
    type: slack.Server
    url: !value "slack_url"
    userName: !value "slack_user"
  - name: Ecommerce
    type: sonar.Server
    url: http://54.227.137.132:9000
    username: admin
    password: !value "sonar_Server_Ecommerce_password"
  - name: Ecommerce
    type: xldeploy.XLDeployServer
    url: http://xld:4516
    username: admin
    password: !value "xldeploy_XLDeployServer_Ecommerce_password"
