apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 10
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-xlr-consul
  name: consul
  namespace: xlr
  selfLink: /apis/apps/v1/namespaces/xlr/deployments/consul
  uid: e0ec3f3c-db70-47a3-8bab-7a00936e8183
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-xlr-consul
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        workload.user.cattle.io/workloadselector: deployment-xlr-consul
    spec:
      containers:
      - image: bitnami/consul:latest
        imagePullPolicy: IfNotPresent
        name: consul
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /bitnami
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: {{ConsulVol1}}
          type: ""
        name: vol1
