language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: srIaPQWVO9JZPXqEZmxGTlVrWJE/qnDa2IK8sqK6KBUs0baCebQEwyHIa/eX1V+LqJFji/0ut/IbmEPwRc97DLsEIYEAXxzMKeyv5U3g5iEP++LwAKowiHEruU33M0vSOFP3tnVj/c7ysSYXg2thr70bJoqTo5QgwjKN4R2H0uQt7eRgnIoOOr9JaRE6qpWrIP1cJYAhAdTV8RdcxRf2cfY8lf9xh+iXjE9ek540wcA4tt0AS3rggOt9LlGbwlNKM4ZXSTZccGYP4bH2adbi8PK0lC3IhZQjjV8IKCgsK/HAk1zKstdKt/jo2MgUzbess5NzU+dRursrvOeQFFzAlvJpHDYkGkv7kqgglw4WggK6fBt/G44aycsdn1N8iCwPubhoO5ebXM+fXkVyjBSCTt24ngJj2Umid8B3dl25WID2LJjK+PDNIb36bQQmkQaJ4coo5VXn+lWXfFIMwpUvVp3wL0mD1I5G/cb1Mg6qw5VG53lUKIyzocon4sPqgvA6x8R2OOtUZUn4iZfvtdiNETnaYFU8uONd7THPbbx6w2firKm7lxgaG3cp9h+Fi8Ttp9V+DFOCjear2ff2s7Br1zot9hGS14qd2Y7dXStUMT+54PYmaMbCQJk3Irx9O4LSFhDGVI7bEVdyiwB/R9+/I6xKMRdLqpzS28tL+1ZGmys=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-windows-file-plugin
notifications:
  slack:
    secure: EIhwYBu3jbhKV4yxKyeTVTtLZmHoSmnjh5L2f+o78rQ1GR437dFNW51eTxcOZRlv2ZxWs0z9KOptMGJnNnM84cDvWuIdxPed5Nno+87YXI4qpGM8fvncvfmH4ftQrcVQcNLXJzGn7L4MXESBh4467bD0eLkUYnipaybdfvZ/j8Bj+LhNR3C/ZY1B+vF1opAJUFttPl8RQMG/KBSGZslyR3G9ZEKrCqmLk0qM/malmyCtGHOSJHS+qtxEf8LnVQ7ivLxzgyPrvDFFQlHaanFDoqP9s119k9FzLV6nDsgCl2+DTnUm1MuKg9l3nnDo6qmMTSDLk58IS6b1jFXWg+rS/2QM7RmzOx7vQcLhp+k+aKCzSUZxyyyW9g1kIKFdc+sn1tmbQY2Hxuj0y8516WCynu4kelYaFy3AFLk0r1RCHBLCYv29fIObzm6ZUJBRovMzCQcTFIgr18BxqSI1RuCWFAFpcM/Q5CJmTyEKTudMcfVJdJ4tAR41TrBdNSVqgmk0opnJa0Z0Cvk5TeEDNFe/Z/UIo3y2vicxYzm6GIqvjSayipGSrSTyVOCs/JVxAXTFnjSXh40GFbFPoofb5J2zF9S4TR+cGtlE90iNQyOIp7IVkm0q4U7r2NNwU3IW7r4+6RYJkZOaq9ccuYlbloihq8WBg2BBvzfMmSGv+rhHUCE=
